const play = window.document.getElementById("play")
var NumberWord = window.document.querySelector(".NumberOfWords")
const word = window.document.getElementById('thing')

play.addEventListener("click" , (e) =>{
    word.innerHTML=''
    const object = getRandomObject();
    word.innerHTML=`${object}`

})



function getRandomObject() {
    const index = Math.floor(Math.random() * objects.length);
    return objects[index];
  }

  const objects = [
    'Guitar',
    'Elephant',
    'Write',
    'Chef',
    'Watch',
    'Lion',
    'Sing',
    'Doctor',
    'Chair',
    'Monkey',
    'Dance',
    'Engineer',
    'Phone',
    'Dog',
    'Cook',
    'Pilot',
    'Lamp',
    'Cat',
    'Draw',
    'Teacher',
    'Car',
    'Bird',
    'Paint',
    'Lawyer',
    'Glasses',
    'Horse',
    'Play',
    'Farmer',
    'Computer',
    'Fish',
    'Swim',
    'Mechanic',
    'Table',
    'Snake',
    'Read',
    'Artist',
    'Book',
    'Giraffe',
    'Run',
    'Writer',
    'Chair',
    'Butterfly',
    'Speak',
    'Accountant',
    'Keyboard',
    'Rabbit',
    'Climb',
    'Architect',
    'Door',
    'Cow',
    'Telescope',
    'Kangaroo',
    'Code',
    'Electrician',
    'Wallet',
    'Octopus',
    'Swim',
    'Firefighter',
    'Sofa',
    'Wolf',
    'Act',
    'Dentist',
    'Bottle',
    'Fox',
    'Repair',
    'Carpenter',
    'Lampshade',
    'Dolphin',
    'Build',
    'Journalist',
    'Motorcycle',
    'Owl',
    'Clap',
    'Barber',
    'Mirror',
    'Cell phone',
    'Tiger',
    'Sing',
    'Photographer',
    'Clock',
    'Gorilla',
    'Bake',
    'Journalist',
    'Raccoon',
    'Sail',
    'Policeman',
    'Guitarist',
    'Hedgehog',
    'Jump',
    'Writer',
    'Waiter',
    'Elephant',
    'Sleep',
    'Painter',
    'Bicycle',
    'Happy',
    'Forest',
    'Swim',
    'Problem',
    'Dance',
    'Elephant',
    'Rules',
    'Mountain',
    'Paint',
    'Sunflower',
    'Laugh',
    'Cloud',
    'Mistake',
    'Moon',
    'Write',
    'List',
    'Rainbow',
    'Sing',
    'Star',
    'Basket',
    'Tree',
    'Problematic',
    'Fish',
    'Goal',
    'Inspire',
    'Compass',
    'Trust',
    'Light',
    'Friendship',
    'Maze',
    'Hope',
    'Travel',
    'Refresh',
    'Butterflies',
    'Treehouse',
    'Excite',
    'Courage',
    'Disguise',
    'Untouchable',
    'Warm',
    'Love',
    'Ocean',
    'Explore',
    'Art',
    'New',
    'Delicious',
    'Colors',
    'The Color Blue',
    'The Color Green',
    'The Color Purble', 
    'The Color Grey',
    'The Color Red',
    'The Color Orange',
    'The Color Pink',
    'The Color White',
    'The Color Black',
    'Upsad',
    'Hungry',
    'Beautiful',
    'Courageous',
    'Enthusiastic',
    'Fascinating',
    'Generous',
    'Humorous',
    'Interesting',
    'Love',
    'Cute',
    'Watch',
    'See',
    'Optimistic',
    'Passionate',
    'Strong',
    'Life',
    'Death',
    'Sand',
    'Island',
    'Country',
    'City',
    'Sword',
    'Stick',
    'Fire',
    'water',
    'Pizza',
    'Sushi',
    'Tacos',
    'Burgers',
    'Pasta',
    'Fried Chicken',
    'Steak',
    'Fish',
    'Chips',
    'Ramen',
    'Lobster',
    'Onion',
    'Garlic',
    'Beans',
    'Rice',
    'Ceviche',
    'Risotto',
    'Castle',
    'Hospital',
    'School',
    'Faculty',
    'Gym',
    'Supermarket',
    'Drugstore',
    'Gamer',
    'Pet',
    'Wood',
    'Glass',
    'Grass',
    'People',
    'WhatsApp',
    'YouTube',
    'Instagram',
    'Facebook',
    'TikTok',
    'LinkedIn',
    'Pinterest',
    'Twitter',
    'Robber',
    'Kid',
    'Clothes',
    'Closet',
    'Floor',
    'Flower',
    'Stone',
    'Bus',
    'Airplane',
    'Shoes',
    'Shirt',
    'Speed' ,
    'Light',
    'Lamp',
    'Eye',
    'Hand', 
    'Head',
    'Body',
    'Tongue',
    'Thinger',
    'Hair',
    'Nose',
    'Day ',
    'Year',
    'Leg',
    'Teeth',
    'Feet ',
    'Mouth',
    'Month',
    'Heart',
    'Dice',
    'Pants',
    'Sock',
    'Soccer',
    'Football',
    'Volleyball',
    'Bag',
    'Neck',
    'Break',
    'Sea',
    'Pen',
    'Paper',
    'Pencil',
    'Scissors',
    'Rock',
    'Bug',
    'Ladybug',
    'Bee',
    'Cat',
    'Ring',
    'Rat',
    'Circle',
    'Brick',
    'Icecream',
    'Chocolate',
    'Alcohol',
    'Coffee',
    'Tea',
    'Milk',
    'Meat',
    'Chicken',
    'Ship',
    'Brazil',
    'China',
    'USA',
    'Canada',
    'Italy',
    'France',
    'South Africa',
    'Beetle',
    'Mouse',
    'Headset',
    'Keys',
    'Keyboard',
    'Desktop',
    'Flipflop',
    'Germany',
    'Knife',
    'Weapon',
    'Fork',
    'Road',
    'Spoon',
    'Silver',
    'Gold',
    'Diamond',
    'Beach'
  ];
  
 NumberWord.innerHTML = `The game have <strong>${objects.length}</strong> words`