const play = window.document.getElementById("play")

const word = window.document.getElementById('thing')

play.addEventListener("click" , (e) =>{
    word.innerHTML=''
    const object = getRandomObject();
    word.innerHTML=`${object}`

})

function getRandomObject() {
    const index = Math.floor(Math.random() * objects.length);
    return objects[index];
  }

  const objects = [
    'Guitar',
    'Elephant',
    'Write',
    'Chef',
    'Watch',
    'Lion',
    'Sing',
    'Doctor',
    'Chair',
    'Monkey',
    'Dance',
    'Engineer',
    'Phone',
    'Dog',
    'Cook',
    'Pilot',
    'Lamp',
    'Cat',
    'Draw',
    'Teacher',
    'Car',
    'Bird',
    'Paint',
    'Lawyer',
    'Glasses',
    'Horse',
    'Play',
    'Farmer',
    'Computer',
    'Fish',
    'Swim',
    'Mechanic',
    'Table',
    'Snake',
    'Read',
    'Artist',
    'Book',
    'Giraffe',
    'Run',
    'Writer',
    'Chair',
    'Butterfly',
    'Speak',
    'Accountant',
    'Keyboard',
    'Rabbit',
    'Climb',
    'Architect',
    'Door',
    'Cow',
    'Telescope',
    'Kangaroo',
    'Code',
    'Electrician',
    'Wallet',
    'Octopus',
    'Swim',
    'Firefighter',
    'Sofa',
    'Wolf',
    'Act',
    'Dentist',
    'Bottle',
    'Fox',
    'Repair',
    'Carpenter',
    'Lampshade',
    'Dolphin',
    'Build',
    'Journalist',
    'Motorcycle',
    'Owl',
    'Clap',
    'Barber',
    'Mirror',
    'Cell phone',
    'Tiger',
    'Sing',
    'Photographer',
    'Clock',
    'Gorilla',
    'Bake',
    'Journalist',
    'Raccoon',
    'Sail',
    'Policeman',
    'Guitarist',
    'Hedgehog',
    'Jump',
    'Writer',
    'Waiter',
    'Elephant',
    'Sleep',
    'Painter'
  ];
  